### ISSUE TITLE
Port this to Ulefone Armor 8 Pro

### ISSUE THREAD

**Issue by vonpupp** [N00bTree/android_device_ulefone_Armor_6#1]
Hello,

I just got an Ulefone Armor 8 Pro. The specs are very close to what is shown on the readme, CPU, chipset and GPU are exactly the same. The only notable differences I spoted are:

8Gb of ram instead of 6Gb.
Shipped with Android 11 instead of Android 8.
There might be others like GPS, camera, batery, etc. I believe/hope these are not relevant to TWRP.
How can I proceed to either compile my own version of TWRP or use any that works on this phone model? If the procedure is "safe" enough, I am willing to contribute to the project with the TWRP port of this model and later a Lineage OS build also if possible.

Any guidance is very welcome. I have never done this but I am somehow experienced in linux. Thank you in advance.

**Comment by lopestom** [comment]
Here's we need trying create a correct device tree for your device with correct informations.
I see your repository Armor 8 Pro and miss very informations from device/recovery.img - So need stock recovery.img to know.
Step 1 - You have recovery.img file from your device?

Find the stock ROM here: [Download](https://drive.google.com/drive/folders/1qT2jMCCTt9Q4PBkBlqU1tg5SeIiFvlqP)
look your model and have the ROM.zip - unzip and have recovery.img

**Comment by lopestom** [comment]
Step 2 - With recovery.img you need have a TWRP device tree generator installed in your PC Linux. Look about How to use and requirements.
[TWRP device tree generator](https://github.com/SebaUbuntu/TWRP-device-tree-generator#twrp-device-tree-generator)

**Comment by lopestom** [comment]
Step 3 - Put your recovery.img file in the folder and write in the terminal:
`python3 -m twrpdtgen recovery.img`

Look output folder create with name of the device and the files for device tree.

**Comment by vonpupp** [comment]
If anyone else is interested, [this repository] is work in progress on the build for Armor 8 Pro.

[this repository]: https://github.com/vonpupp/android_device_ulefone_armor_8_pro
